# YOUR NAME OR TITLE OF YOUR SITE
name: DexZ Bot - ABOUT

# YOUR BRAND/PERSONAL TAGLINE
tagline: Olá! Siga abaixo mais informações sobre mim!

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/harsh98trivedi.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: fidelo34k
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://x.com
    Username: fidelo34k
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

     # THREADS.NET
  - Name: Threads
    URL: https://threads.net
    Username: fidelo34k
    Color: '#000000'
    Icon-Class: fa-brands fa-threads
    Text_Color: '#ffffff'

   
    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCS3zvA_2r1iGT7MB3NVCGAw
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GRUPO DEXZ
  - Name: DexZ Bot
    URL: https://chat.whatsapp.com/ITzzMMfgsxdL73WJKmpq0G
    Username: 
    Color: '#1DB954'
    Icon-Class: fab fa-whatsapp

   
    # EMAIL
  - Name: Email
    URL: 'botdexz@gmail.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


  -
  #   # DISCORD
   - Name: Discord
   URL: 'https://discord.com/invite/zKz6DW35Ct'
    Username: 
    Icon-Class: fab fa-discord
    Color: '#5865F2'
    Text_Color: '#ffffff'

    
    

  #TIKTOK
   Name: TikTok
    URL: https://www.tiktok.com
     Username: 
     Color: '#FE2C55'
   Icon-Class: fab fa-tiktok

  


 
# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
