# YOUR NAME OR TITLE OF YOUR SITE
name: Felipe Fidelo

# YOUR BRAND/PERSONAL TAGLINE
tagline: Olá, Segue abaixo algumas informações sobre mim!

# YOUR/BRAND IMAGE URL
Image_URL: https://telegra.ph/file/bdccc0814297dcee46811.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
   
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: fidelo34k
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://x.com
    Username: fidelo34k
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

     # THREADS.NET
  - Name: Threads
    URL: https://threads.net
    Username: fidelo34k
    Color: '#000000'
    Icon-Class: fa-brands fa-threads
    Text_Color: '#ffffff'

 # Gupo dexz bot
  - Name: DexZ Bot
    URL: https://chat.whatsapp.com/ITzzMMfgsxdL73WJKmpq0G
    Username: 
    Color: '#1DB954'
    Icon-Class: fab fa-whatsapp
    Text_Color: '#ffffff'
   

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
